name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: logindocker
      run: docker login -u xyz -p dckr_pat_xyz
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lpkyrius/nsapi
    - name: Push the Docker image
      run: docker push lpkyrius/nsapi
